name: coverage

on: [ push, pull_request ]

env:
    CARGO_TERM_COLOR: always

jobs:
    coverage:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Run tests
                run: cargo test --verbose

            -   name: Run rust grcov for code coveragre report
                uses: actions-rs/grcov@v0.1.5

            -   name: Upload this report to Codecov
                uses: codecov/codecov-action@v1.0.7